import { Share } from 'react-native';

function formatPeso(n) {
  const num = Number(n || 0);
  return `₱${num.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatPeriodLabel(item) {
  const start = new Date(item.period_start);
  const timeZone = 'Asia/Manila';

  if (item.period_type === 'daily') {
    return start.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric', timeZone });
  }
  if (item.period_type === 'weekly') {
    const monday = new Date(start);
    const dayOfWeek = monday.getDay();
    const daysToMonday = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
    monday.setDate(monday.getDate() + daysToMonday);
    
    const sunday = new Date(monday);
    sunday.setDate(monday.getDate() + 6);
    
    const s = monday.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', timeZone });
    const e = sunday.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', timeZone });
    return `${s} - ${e}`;
  }
  if (item.period_type === 'monthly') {
    return start.toLocaleDateString('en-PH', { month: 'long', year: 'numeric', timeZone });
  }
  return 'Unknown';
}

export const exportBreakevenReport = async (data = [], frequency = 'Daily') => {
  try {
    const reportDate = new Date().toLocaleDateString('en-PH', {
      timeZone: 'Asia/Manila',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    let reportText = `TarTrack Breakeven Report (${frequency})
Generated on ${reportDate}

`;

    if (!data || data.length === 0) {
      reportText += 'No breakeven data available for the selected period.';
    } else {
      reportText += `BREAKEVEN SUMMARY
${'='.repeat(50)}

`;
      
      data.forEach((item, index) => {
        const earnings = Number(item.revenue_driver) || 0;
        const expenses = Number(item.expenses) || 0;
        const profit = earnings - expenses;
        const breakevenHit = earnings >= expenses;
        const profitable = profit > 0;
        
        let status = 'Below Breakeven';
        if (breakevenHit && profitable) status = 'Breakeven + Profit';
        else if (breakevenHit && !profitable) status = 'Breakeven, No Profit';
        
        reportText += `${index + 1}. ${formatPeriodLabel(item)}
`;
        reportText += `   Status: ${status}
`;
        reportText += `   Earnings: ${formatPeso(earnings)}
`;
        reportText += `   Expenses: ${formatPeso(expenses)}
`;
        reportText += `   Profit/Loss: ${formatPeso(profit)}
`;
        if (item.total_bookings) {
          reportText += `   Total Rides: ${item.total_bookings}
`;
        }
        reportText += `
`;
      });
      
      // Summary statistics
      const totalEarnings = data.reduce((sum, item) => sum + (Number(item.revenue_driver) || 0), 0);
      const totalExpenses = data.reduce((sum, item) => sum + (Number(item.expenses) || 0), 0);
      const totalProfit = totalEarnings - totalExpenses;
      const breakevenPeriods = data.filter(item => (Number(item.revenue_driver) || 0) >= (Number(item.expenses) || 0)).length;
      
      reportText += `OVERALL SUMMARY
${'='.repeat(50)}
`;
      reportText += `Total Periods: ${data.length}
`;
      reportText += `Breakeven Periods: ${breakevenPeriods}
`;
      reportText += `Success Rate: ${data.length > 0 ? ((breakevenPeriods / data.length) * 100).toFixed(1) : 0}%
`;
      reportText += `Total Earnings: ${formatPeso(totalEarnings)}
`;
      reportText += `Total Expenses: ${formatPeso(totalExpenses)}
`;
      reportText += `Net Profit/Loss: ${formatPeso(totalProfit)}
`;
    }

    reportText += `

Generated by TarTrack App`;

    await Share.share({
      message: reportText,
      title: `Breakeven Report - ${frequency}`,
    });

    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
};

// Keep the old function for backward compatibility
export const exportBreakevenImage = exportBreakevenReport;